### ISSUE TITLE
no push notification

### ISSUE THREAD

**Issue by abadoliverco** [ashwin-phadke/ZappChatt#1]
I tried, but no push notification.

**Comment by ashwin-phadke** [comment]
The FCMNotificationBuilder activity needs your servers api key in order to function, have you put in your servers api key?

**Comment by abadoliverco** [comment]
@ashwin-phadke your FCMNotificationBuilder activity is never used in your project.

**Comment by ashwin-phadke** [comment]
A PR is welcome on this issue .
