### ISSUE TITLE
Help with getting Current User Id plz plz plz plz

### ISSUE THREAD

**Issue by blazingdevil44** [ashwin-phadke/ZappChatt#3]
I made a new fragment in this code  but I cant get the current User Id not matter what I do can someone plz help me I have tried many things but it seems I have to get the current User id form within the already present code somehow can some one plz help

**Comment by ashwin-phadke** [comment]
There is a string already available in the User model for saving the username that you can use to access usernames of the registered users.
Go through that section so that you will get an idea of getting the username.
